# Generated by Django 4.2.5 on 2023-09-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_remove_contactus_country_remove_contactus_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
