# Generated by Django 4.2.5 on 2023-09-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_navigation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Slider', 'Slider'), ('Home/About', 'Home/About'), ('Features', 'Features'), ('Features_1', 'Features_1'), ('Home/Video', 'Home/Video'), ('Achievements', 'Achievements'), ('Achievements_1', 'Achievements_1'), ('Testimonials', 'Testimonials'), ('Blog', 'Blog'), ('Services', 'Services'), ('Vision', 'Vision'), ('Mission', 'Mission'), ('Objectives', 'Objectives'), ('Our Strength', 'Our Strength'), ('Research & Development', 'Research & Development'), ('Video_Gallery', 'Video_Gallery'), ('Gallery', 'Gallery'), ('Image_Gallery', 'Image_Gallery'), ('Contact', 'Contact'), ('Group', 'Group')], max_length=50, null=True),
        ),
    ]
