# Generated by Django 4.2.5 on 2023-09-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='image',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
    ]
