# Generated by Django 4.2.5 on 2023-09-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_navigation_video_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='mobileno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
