# Generated by Django 4.2.5 on 2023-10-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='QRCODE/'),
        ),
    ]
