# Generated by Django 4.2.5 on 2023-10-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0028_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='check_in',
            field=models.DateField(default='2012-12-12', null=True),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='check_out',
            field=models.DateField(default='2012-12-12', null=True),
        ),
    ]
